# Generated by Django 3.2.1 on 2021-05-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='available_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='available quantity'),
        ),
    ]
